### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by vishmit** [vitorfs/bootcamp#61] opened 2016-10-01 19:58 UTC
I am very new to the django framework so don't have much idea about it. Can you guide me how to install this project. On executing manage.py migrate i am getting this error : FATAL:  password authentication failed for user "u_bootcamp".

**Comment by elbaloo** [comment] 2016-10-03 22:12
Are you following https://github.com/vitorfs/bootcamp/wiki/Installing-and-Running-Bootcamp?

**Comment by vishmit** [comment] 2016-10-04 07:38
yeah i followed the steps but i am not able to install psycopg2==2.6.1.

getting this error:

Downloading/unpacking psycopg2
  Running setup.py egg_info for package psycopg2

    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.
    Complete output from command python setup.py egg_info:
    running egg_info

writing pip-egg-info/psycopg2.egg-info/PKG-INFO
writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
warning: manifest_maker: standard file '-c' not found

Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

----------------------------------------
Command python setup.py egg_info failed with error code 1

**Comment by sebastian-code** [comment] 2016-10-04 14:22
Hi @vishmit your issue is related to your PostgreSQL engine, psycopg2 is the Python connector for Postgres, that error means the installation process is not able to find your Postgres installation, meaning than probably you have not installed Postgres, or is not properly installed.

That said, if you're not going to work with Postgres but with SQLite instead, then you can ignore safely that package.

**Comment by sebastian-code** [comment] 2016-11-26 12:47
@vishmit did you solved this? do you need additional help? if this is already solved, do you mind to close it?

**Comment by sebastian-code** [comment] 2016-11-26 19:12
Closing if there is no need for further information.

**Closed by sebastian-code** 2016-11-26 19:12 UTC

**Comment by tarasha** [comment] 2018-03-27 01:08
I get the same exact same error when I run the pip3 install... requirements/local.txt
I am unable to find the reason why. Can you please suggest?

**Comment by sebastian-code** [comment] 2018-03-27 01:44
Hi @tarasha. The issue is related to the way psycopg2 has to be installed and its requirements, not just to be able to compile, but also the validation it does on the PostgreSQL installation.
